export interface FamousPerson {
  slug: string;         // pinyin URL slug
  name: string;         // Chinese name
  nameEn: string;       // English name
  era: string;          // 年代
  domain: string;       // 領域
  formations: string[]; // 格局
  soulPalace: string;   // 命宮
  mainStars: string;    // 主星
  fiveElements: string; // 五行局
  brief: string;        // 簡介
  birthLabel: string;   // 出生時間標註
  gender?: "male" | "female"; // defaults to "male" if omitted
}

export const FAMOUS_PEOPLE: FamousPerson[] = [
  {
    slug: "li-xiaolong",
    name: "李小龍",
    nameEn: "Bruce Lee",
    era: "1940–1973",
    domain: "武術·電影·哲學",
    formations: ["府相朝垣格", "羊陀夾忌格"],
    soulPalace: "未",
    mainStars: "天相",
    fiveElements: "木三局",
    brief: "截拳道創始人、武術宗師、演員與哲學家。府相朝垣格讓他兼具領導力與開創精神，33歲的人生燭火照耀世界。",
    birthLabel: "1940年11月27日 卯時",
  },
  {
    slug: "mozart",
    name: "莫札特",
    nameEn: "Wolfgang Amadeus Mozart",
    era: "1756–1791",
    domain: "古典音樂",
    formations: ["殺破狼格", "火貪格"],
    soulPalace: "卯",
    mainStars: "廉貞·破軍",
    fiveElements: "土五局",
    brief: "古典音樂神童，殺破狼格的極端體現——天才如火焰燃燒，創作600餘部作品後在35歲化為灰燼。",
    birthLabel: "1756年1月27日 戌時",
  },
  {
    slug: "einstein",
    name: "愛因斯坦",
    nameEn: "Albert Einstein",
    era: "1879–1955",
    domain: "物理學·哲學",
    formations: ["殺破狼格", "極居卯酉格"],
    soulPalace: "酉",
    mainStars: "紫微·貪狼",
    fiveElements: "金四局",
    brief: "相對論創始人，紫微貪狼坐命的極居卯酉格，帝王星制約慾望星，將破壞性衝動昇華為科學革命。",
    birthLabel: "1879年3月14日 午時",
  },
  {
    slug: "zhang-guorong",
    name: "張國榮",
    nameEn: "Leslie Cheung",
    era: "1956–2003",
    domain: "音樂·電影",
    formations: ["日月並明格", "府相朝垣格"],
    soulPalace: "酉",
    mainStars: "天府",
    fiveElements: "火六局",
    brief: "香港樂壇與影壇巨星，天府坐命酉宮，日月並明格賦予他全方位的天才氣質與雍容風華，47歲以決絕方式謝幕，成為一代人永遠的遺憾。",
    birthLabel: "1956年9月12日 子時",
  },
  {
    slug: "jinyong",
    name: "金庸",
    nameEn: "Jin Yong",
    era: "1924–2018",
    domain: "武俠小說·新聞",
    formations: ["祿馬交馳格", "府相朝垣格"],
    soulPalace: "子",
    mainStars: "武曲·天府",
    fiveElements: "水二局",
    brief: "武俠小說宗師，祿馬交馳格造就財祿賓士與筆耕不輟的傳奇人生，《射鵰英雄傳》《天龍八部》影響華人世界數代讀者，94歲高壽而終。",
    birthLabel: "1924年3月10日 卯時",
  },
  {
    slug: "mayun",
    name: "馬雲",
    nameEn: "Jack Ma",
    era: "1964–",
    domain: "企業家·科技",
    formations: ["殺破狼格", "祿馬交馳格", "日月照壁格"],
    soulPalace: "辰",
    mainStars: "貪狼",
    fiveElements: "木三局",
    brief: "阿里巴巴創始人，殺破狼格賦予顛覆性創業精神，祿馬交馳帶來滾滾財源，從高考落榜三次的英語教師到全球商業帝國締造者。",
    birthLabel: "1964年9月10日 巳時",
  },
  {
    slug: "zhoujielun",
    name: "周杰倫",
    nameEn: "Jay Chou",
    era: "1979–",
    domain: "音樂·電影",
    formations: ["日月並明格", "府相朝垣格"],
    soulPalace: "酉",
    mainStars: "天府",
    fiveElements: "木三局",
    brief: "華語流行音樂天王，天府坐命酉宮，日月並明格造就耀眼明星氣場，開創中國風與嘻哈融合的音樂風格，成為一代人不可替代的青春記憶。",
    birthLabel: "1979年1月18日 卯時",
  },
  {
    slug: "napolun",
    name: "拿破崙",
    nameEn: "Napoleon Bonaparte",
    era: "1769–1821",
    domain: "軍事·政治",
    formations: ["殺破狼格"],
    soulPalace: "寅",
    mainStars: "七殺",
    fiveElements: "火六局",
    brief: "法國皇帝與歐洲最偉大的軍事統帥，七殺坐命寅宮的殺破狼格典型體現——以顛覆之勢橫掃歐洲，《拿破崙法典》奠定現代法律基石，終兵敗流亡51歲離世。",
    birthLabel: "1769年8月15日 午時",
  },
  {
    slug: "julifuren",
    name: "居里夫人",
    nameEn: "Marie Curie",
    era: "1867–1934",
    domain: "科學·物理",
    formations: ["火貪格", "府相朝垣格"],
    soulPalace: "巳",
    mainStars: "天相",
    fiveElements: "火六局",
    brief: "史上首位兩度獲諾貝爾獎的科學家，火貪格賦予她突破常規的探索精神，天相坐命巳宮映照出在19世紀男性科學界中頑強堅守的鐵血品格。",
    birthLabel: "1867年11月7日 午時",
    gender: "female",
  },
  {
    slug: "qiaobusi",
    name: "喬布斯",
    nameEn: "Steve Jobs",
    era: "1955–2011",
    domain: "科技·創業",
    formations: ["鈴貪格"],
    soulPalace: "亥",
    mainStars: "天同",
    fiveElements: "土五局",
    brief: "Apple創始人，鈴貪格帶來驟然迸發的靈感與顛覆性創造力，從車庫創業到改寫個人電腦、音樂、手機三個時代，以「活著是為了改變世界」的信念燃盡56年人生。",
    birthLabel: "1955年2月24日 卯時",
  },
  {
    slug: "masike",
    name: "馬斯克",
    nameEn: "Elon Musk",
    era: "1971–",
    domain: "科技·企業家",
    formations: ["機月同梁格"],
    soulPalace: "寅",
    mainStars: "天機·太陰",
    fiveElements: "木三局",
    brief: "SpaceX與特斯拉創始人，機月同梁格賦予超凡的系統思維與理性規劃力，以人類移民火星為終極目標，多次跌入破產邊緣又東山再起，不斷突破科技極限。",
    birthLabel: "1971年6月28日 卯時",
  },
  {
    slug: "lilianjie",
    name: "李連杰",
    nameEn: "Jet Li",
    era: "1963–",
    domain: "武術·電影",
    formations: ["君臣慶會格", "殺破狼格", "日月照壁格"],
    soulPalace: "丑",
    mainStars: "紫微·破軍",
    fiveElements: "金四局",
    brief: "五屆全國武術冠軍、功夫電影宗師，紫微破軍坐命丑宮，君臣慶會格與殺破狼格並現——帝王氣質與破格精神交融，從《少林寺》到好萊塢，晚年轉向慈善公益。",
    birthLabel: "1963年4月26日 卯時",
  },
  {
    slug: "meiyafang",
    name: "梅豔芳",
    nameEn: "Anita Mui",
    era: "1963–2003",
    domain: "音樂·電影",
    formations: ["命無正曜格", "日月照壁格"],
    soulPalace: "卯",
    mainStars: "空宮",
    fiveElements: "水二局",
    brief: "香港樂壇「百變天后」，命無正曜格造就難以捉摸的命運底色，日月照壁格帶來舞臺上的耀目光彩，一生摯愛事業與友情，40歲身著婚紗告別演唱會謝幕，令無數人動容。",
    birthLabel: "1963年10月10日 午時",
    gender: "female",
  },
  {
    slug: "renzhengnei",
    name: "任正非",
    nameEn: "Ren Zhengfei",
    era: "1944–",
    domain: "科技·企業家",
    formations: ["祿馬交馳格", "府相朝垣格", "三奇加會格", "日月照壁格"],
    soulPalace: "午",
    mainStars: "破軍",
    fiveElements: "土五局",
    brief: "華為創始人，祿馬交馳格與三奇加會格疊加，賦予他橫跨全球的商業疆域與超凡戰略眼光，帶領華為從一家小交換機代理商成長為全球5G技術領導者，以一己之力撐起中國科技自主的脊樑。",
    birthLabel: "1944年10月25日 卯時",
  },
  {
    slug: "liuyifei",
    name: "劉亦菲",
    nameEn: "Liu Yifei",
    era: "1987–",
    domain: "電影·演藝",
    formations: ["機月同梁格", "火貪格", "三奇加會格", "日月照壁格", "羊陀夾忌格"],
    soulPalace: "子",
    mainStars: "貪狼",
    fiveElements: "木三局",
    brief: "「神仙姐姐」劉亦菲，三奇加會格與機月同梁格疊加，賦予她超凡的藝術感知力與國際視野，從古裝仙女到好萊塢花木蘭，以空靈氣質跨越文化疆界，成為享譽全球的華人影星。",
    birthLabel: "1987年8月25日 卯時",
    gender: "female",
  },
  {
    slug: "liudehua",
    name: "劉德華",
    nameEn: "Andy Lau",
    era: "1961–",
    domain: "音樂·電影",
    formations: ["日月並明格", "機月同梁格"],
    soulPalace: "戌",
    mainStars: "太陰",
    fiveElements: "木三局",
    brief: "香港四大天王之首，日月並明格賦予他兼具太陽般光芒與月亮般溫潤的雙面魅力，機月同梁格造就敬業謙遜的藝人底色，在娛樂圈深耕逾四十年而魅力不減，成為華人世界跨越時代的不朽符號。",
    birthLabel: "1961年9月27日 午時",
  },
  {
    slug: "liuxiang",
    name: "劉翔",
    nameEn: "Liu Xiang",
    era: "1983–",
    domain: "田徑·體育",
    formations: ["鈴貪格", "日月照壁格"],
    soulPalace: "丑",
    mainStars: "巨門",
    fiveElements: "金四局",
    brief: "中國飛人，鈴貪格帶來驟然迸發的驚世才華，2004年雅典奧運會以12.91秒打破世界紀錄，將黃種人田徑帶上世界之巔；日月照壁格則讓他在逆境與傷病中仍燃燒出不屈意志，書寫體育傳奇。",
    birthLabel: "1983年7月13日 卯時",
  },
  {
    slug: "yaoming",
    name: "姚明",
    nameEn: "Yao Ming",
    era: "1980–",
    domain: "籃球·體育",
    formations: ["丹墀桂墀格"],
    soulPalace: "丑",
    mainStars: "巨門",
    fiveElements: "火六局",
    brief: "中國籃球巨人，丹墀桂墀格造就聲名遠播與文武兼備的傳奇氣象，以226cm之軀征服NBA八載，退役後轉型體育管理與商業投資，成為國際體壇最具影響力的中國面孔。",
    birthLabel: "1980年9月12日 午時",
  },
  {
    slug: "gongli",
    name: "鞏俐",
    nameEn: "Gong Li",
    era: "1965–",
    domain: "電影·演藝",
    formations: ["命無正曜格"],
    soulPalace: "未",
    mainStars: "武曲",
    fiveElements: "木三局",
    brief: "中國影壇第一人，命無正曜格造就借光綻放的獨特命運，遷移宮日月相照賦予她跨越東西的國際氣場，憑《紅高粱》揚名威尼斯、戛納，以東方女性之美在世界電影史留下不可磨滅的印記。",
    birthLabel: "1965年12月31日 午時",
    gender: "female",
  },
  {
    slug: "zhangxueyou",
    name: "張學友",
    nameEn: "Jacky Cheung",
    era: "1961–",
    domain: "音樂·電影",
    formations: [],
    soulPalace: "辰",
    mainStars: "廉貞",
    fiveElements: "水二局",
    brief: "華語樂壇「歌神」，命盤無特定格局卻以孤星之力成就不凡——廉貞坐命辰宮，歷經酗酒低谷後浴火重生，用真實情感與無懈可擊的唱功感動數代人，全球唱片銷量逾1億張，成為華人流行音樂的永恆豐碑。",
    birthLabel: "1961年9月10日 卯時",
  },
  {
    slug: "chenlong",
    name: "成龍",
    nameEn: "Jackie Chan",
    era: "1954–",
    domain: "武術·電影",
    formations: ["府相朝垣格", "日月照壁格", "火鈴夾命格"],
    soulPalace: "卯",
    mainStars: "文曲",
    fiveElements: "火六局",
    brief: "國際功夫巨星，府相朝垣格賦予天生的領袖氣場與開創精神，以不用替身的真實特技闖入好萊塢，將中國功夫與喜劇融為一體，用超過200部電影書寫華人在世界影壇最輝煌的跨文化傳奇。",
    birthLabel: "1954年4月7日 卯時",
  },
  {
    slug: "lining",
    name: "李寧",
    nameEn: "Li Ning",
    era: "1963–",
    domain: "體操·商業",
    formations: [],
    soulPalace: "巳",
    mainStars: "武曲",
    fiveElements: "土五局",
    brief: "「體操王子」與國民品牌締造者，天同廟旺坐命帶來靈動福氣與轉型韌性，三屆奧運會奪得6枚獎章後華麗轉身創業，將「李寧」打造成中國體育用品第一品牌，詮釋運動員跨界商業的最佳範本。",
    birthLabel: "1963年9月8日 卯時",
  },
  {
    slug: "bill-gates",
    name: "比爾·蓋茨",
    nameEn: "Bill Gates",
    era: "1955–",
    domain: "科技·慈善",
    formations: ["日月並明格", "月朗天門格", "陽梁昌祿格"],
    soulPalace: "亥",
    mainStars: "巨門",
    fiveElements: "土五局",
    brief: "微軟創始人與全球最慷慨的慈善家，日月並明格疊加月朗天門格，造就科技洞見與慈悲情懷並重的傳奇人生，從哈佛輟學創業到改寫個人計算時代，退休後以蓋茨基金會矢志消滅全球貧病。",
    birthLabel: "1955年10月28日 子時",
  },
  {
    slug: "wangfei",
    name: "王菲",
    nameEn: "Faye Wong",
    era: "1969–",
    domain: "音樂·演藝",
    formations: ["殺破狼格", "貪武同行格", "風流彩杖格"],
    soulPalace: "未",
    mainStars: "武曲",
    fiveElements: "土五局",
    brief: "華語樂壇「天后」，殺破狼格賦予她顛覆一切的先鋒精神，貪武同行格造就財富與魅力並駕的傳奇氣場，以空靈嗓音與無懼世俗的個性開創中國風融合獨立音樂先河，成為一代人無可替代的精神圖騰。",
    birthLabel: "1969年8月8日 卯時",
    gender: "female",
  },
  {
    slug: "zhangziyi",
    name: "章子怡",
    nameEn: "Zhang Ziyi",
    era: "1979–",
    domain: "電影·演藝",
    formations: ["君臣慶會格", "殺破狼格", "風流彩杖格"],
    soulPalace: "亥",
    mainStars: "巨門",
    fiveElements: "火六局",
    brief: "國際影壇傳奇，君臣慶會格疊加殺破狼格，造就帝王氣質與破格精神交融的強悍命格，憑《臥虎藏龍》《藝伎回憶錄》揚名好萊塢，成為首位躋身世界級票房女星的華人演員，代表中國電影走向世界。",
    birthLabel: "1979年2月9日 午時",
    gender: "female",
  },
  {
    slug: "beizuosi",
    name: "貝佐斯",
    nameEn: "Jeff Bezos",
    era: "1964–",
    domain: "科技·企業家",
    formations: ["機月同梁格"],
    soulPalace: "寅",
    mainStars: "天機",
    fiveElements: "水二局",
    brief: "亞馬遜與藍色起源創始人，機月同梁格賦予超凡洞察力與系統謀略，從車庫網上書店起步構建全球最大電商帝國，進而以太空探索為終極理想，將商業版圖從地球延伸至星辰大海。",
    birthLabel: "1964年1月12日 卯時",
  },
  {
    slug: "denglinjun",
    name: "鄧麗君",
    nameEn: "Teresa Teng",
    era: "1953–1995",
    domain: "音樂·演藝",
    formations: [],
    soulPalace: "未",
    mainStars: "武曲",
    fiveElements: "水二局",
    brief: "華人音樂史上最具影響力的歌手，命宮天機配合福德宮太陰形成文華隱曜之象，以溫柔而深情的嗓音跨越兩岸三地與東南亞，「小城故事」「月亮代表我的心」傳唱至今，42歲早逝留下永恆遺憾與無盡思念。",
    birthLabel: "1953年1月29日 卯時",
    gender: "female",
  },
  {
    slug: "guofucheng",
    name: "郭富城",
    nameEn: "Aaron Kwok",
    era: "1965–",
    domain: "音樂·電影",
    formations: [],
    soulPalace: "卯",
    mainStars: "文曲",
    fiveElements: "土五局",
    brief: "香港四大天王之「舞王」，天機巨門坐命卯宮形成機巨同臨的靈動氣場，以無與倫比的舞臺表現力與精湛舞技獨步華語娛樂圈，演藝之路歷經三十餘載長盛不衰，晚年轉型影壇屢獲國際獎項肯定。",
    birthLabel: "1965年10月26日 午時",
  },
  {
    slug: "chenyixun",
    name: "陳奕迅",
    nameEn: "Eason Chan",
    era: "1974–",
    domain: "音樂·演藝",
    formations: ["府相朝垣格", "三奇加會格"],
    soulPalace: "辰",
    mainStars: "廉貞",
    fiveElements: "木三局",
    brief: "華語樂壇「Eason」，府相朝垣格與三奇加會格疊加造就貴氣與才情並重的音樂大師，以無可挑剔的演唱技巧跨越粵語與普通話兩界，《十年》《富士山下》感動無數人心，成為21世紀華語流行音樂的標誌人物。",
    birthLabel: "1974年7月27日 卯時",
  },
  {
    slug: "leijun",
    name: "雷軍",
    nameEn: "Lei Jun",
    era: "1969–",
    domain: "科技·企業家",
    formations: ["日月並明格", "命無正曜格"],
    soulPalace: "午",
    mainStars: "破軍",
    fiveElements: "土五局",
    brief: "小米創始人與中國科技創業教父，日月並明格賦予領導力與謀略智慧的完美平衡，「為發燒而生」的產品哲學顛覆手機行業，以網際網路思維重塑傳統制造業，更跨界造車挑戰特斯拉，詮釋中國創業者永不言敗的精神底色。",
    birthLabel: "1969年12月16日 卯時",
  },
  {
    slug: "mahuateng",
    name: "馬化騰",
    nameEn: "Pony Ma",
    era: "1971–",
    domain: "科技·企業家",
    formations: ["日月並明格"],
    soulPalace: "巳",
    mainStars: "武曲",
    fiveElements: "水二局",
    brief: "騰訊創始人與「社交帝國」締造者，日月並明格賦予洞察人性的卓越智慧，從一個小小的QQ即時通訊軟體出發，構建起微信、遊戲、金融、雲端計算全生態帝國，以「連線一切」的願景深刻改變十億中國人的數字生活。",
    birthLabel: "1971年10月29日 亥時",
  },
  {
    slug: "luxun",
    name: "魯迅",
    nameEn: "Lu Xun",
    era: "1881–1936",
    domain: "文學·思想",
    formations: ["石中隱玉格", "日月照壁格", "丹墀桂墀格"],
    soulPalace: "午",
    mainStars: "破軍",
    fiveElements: "金四局",
    brief: "中國現代文學之父，石中隱玉格將巨門之暗化為犀利批判的筆鋒，以《吶喊》《彷徨》解剖國民靈魂，「橫眉冷對千夫指，俯首甘為孺子牛」道盡其一生擔當，55歲含恨而終，精神遺產卻永照中華文明。",
    birthLabel: "1881年9月25日 午時",
  },
  {
    slug: "liming",
    name: "黎明",
    nameEn: "Leon Lai",
    era: "1966–",
    domain: "音樂·電影",
    formations: ["機月同梁格", "命無正曜格", "丹墀桂墀格"],
    soulPalace: "寅",
    mainStars: "空宮",
    fiveElements: "木三局",
    brief: "香港四大天王之「偶像派天王」，機月同梁格與命無正曜格疊加造就借力成勢的傳奇命運，以俊朗外形與清新歌聲橫掃亞洲，跨足音樂、電影、時尚設計三界，成為華人娛樂圈最具商業價值的全能藝人之一。",
    birthLabel: "1966年12月10日 卯時",
  },
  {
    slug: "picasso",
    name: "畢加索",
    nameEn: "Pablo Picasso",
    era: "1881–1973",
    domain: "繪畫·現代藝術",
    formations: ["紫府同宮格", "百官朝拱格"],
    soulPalace: "寅",
    mainStars: "紫微·天府",
    fiveElements: "木三局",
    brief: "現代藝術最具影響力的巨匠之一，紫微天府同宮於寅宮，尊貴穩重與開創才華兼備，一生創作逾五萬件作品，是少數在世時便享盡財富與聲望的藝術家。",
    birthLabel: "1881年10月25日 申時（約15:00）",
  },
  {
    slug: "sun-yat-sen",
    name: "孫中山",
    nameEn: "Sun Yat-sen",
    era: "1866–1925",
    domain: "革命·政治",
    formations: ["財蔭夾印格", "府相朝垣格"],
    soulPalace: "辰",
    mainStars: "紫微·天相",
    fiveElements: "水二局",
    brief: "近代中國革命先驅，紫微天相坐命辰宮，財蔭夾印格助其屢獲海外僑胞資助與同志擁護，終結兩千年帝制，被尊為「國父」。",
    birthLabel: "1866年11月12日 未時（約13:00）",
  },
  {
    slug: "mandela",
    name: "曼德拉",
    nameEn: "Nelson Mandela",
    era: "1918–2013",
    domain: "政治·人權運動",
    formations: ["刑囚夾印格"],
    soulPalace: "午",
    mainStars: "廉貞·天相",
    fiveElements: "火六局",
    brief: "南非首位黑人總統，廉貞天相坐命午宮，刑囚夾印格應驗其27年鐵窗生涯，出獄後卻以寬恕化解仇恨，終結種族隔離制度。",
    birthLabel: "1918年7月18日 丑時（約01:00）",
  },
  {
    slug: "messi",
    name: "梅西",
    nameEn: "Lionel Messi",
    era: "1987–",
    domain: "體育·足球",
    formations: ["日照雷門格", "日月並明格"],
    soulPalace: "卯",
    mainStars: "太陽·天梁",
    fiveElements: "金四局",
    brief: "阿根廷球王，太陽天梁坐命卯宮，日照雷門格如旭日東升、光芒普照足壇，七度奪得金球獎，率隊登上世界盃冠軍寶座。",
    birthLabel: "1987年6月24日 卯時（約05:00）",
  },
  {
    slug: "lincoln",
    name: "林肯",
    nameEn: "Abraham Lincoln",
    era: "1809–1865",
    domain: "政治·領導",
    formations: ["馬頭帶箭格", "殺破狼格"],
    soulPalace: "午",
    mainStars: "破軍",
    fiveElements: "火六局",
    brief: "美國第16任總統，擎羊天馬會於命宮午位，馬頭帶箭格賦予其臨危不亂的決斷力，領導聯邦度過南北戰爭，終結奴隸制度。",
    birthLabel: "1809年2月12日 未時（約13:00）",
  },
  {
    slug: "pope-john-paul-ii",
    name: "若望保祿二世",
    nameEn: "Pope John Paul II",
    era: "1920–2005",
    domain: "宗教·領導",
    formations: ["七殺朝鬥格"],
    soulPalace: "午",
    mainStars: "七殺",
    fiveElements: "木三局",
    brief: "天主教史上任期第三長的教宗，七殺坐命午宮朝向北極，七殺朝鬥格賦予其威權與魄力，任內大力推動終結東歐共產政權。",
    birthLabel: "1920年5月18日 亥時（約21:00）",
  },
  {
    slug: "michael-jordan",
    name: "麥可喬丹",
    nameEn: "Michael Jordan",
    era: "1963–",
    domain: "體育·籃球",
    formations: ["百官朝拱格"],
    soulPalace: "酉",
    mainStars: "紫微·貪狼",
    fiveElements: "木三局",
    brief: "籃球史上最具代表性的球星，紫微貪狼坐命酉宮，百官朝拱格輔星盡會，六奪NBA總冠軍，尊貴之氣至今無人能及。",
    birthLabel: "1963年2月17日 巳時（約09:00）",
  },
  {
    slug: "da-vinci",
    name: "達文西",
    nameEn: "Leonardo da Vinci",
    era: "1452–1519",
    domain: "藝術·科學·發明",
    formations: ["鈴昌陀武格"],
    soulPalace: "戌",
    mainStars: "紫微·天相",
    fiveElements: "金四局",
    brief: "文藝復興全才，紫微天相坐命戌宮，鈴昌陀武格對應其一生為之所苦的內耗——大量委託作品因反覆推敲而未能完成，天才與拖延如影隨形。",
    birthLabel: "1452年4月15日 午時（約11:00）",
  },
  {
    slug: "newton",
    name: "牛頓",
    nameEn: "Isaac Newton",
    era: "1643–1727",
    domain: "物理學·數學",
    formations: ["明珠出海格"],
    soulPalace: "子",
    mainStars: "天同·太陰",
    fiveElements: "木三局",
    brief: "近代物理學奠基者，天同太陰坐命子宮旺地，明珠出海格應驗其才華以異途顯露——長年隱居鄉間潛心研究，終以《自然哲學的數學原理》一舉成名。",
    birthLabel: "1643年1月4日 子時（約23:00）",
  },
  {
    slug: "obama",
    name: "歐巴馬",
    nameEn: "Barack Obama",
    era: "1961–",
    domain: "政治·領導",
    formations: ["極向離明格", "日月並明格"],
    soulPalace: "午",
    mainStars: "紫微",
    fiveElements: "金四局",
    brief: "美國首位非裔總統，紫微坐命午宮向陽，極向離明格賦予其剛斷英明的領導特質，任內推動醫療改革，聲望歷久不衰。",
    birthLabel: "1961年8月4日 丑時（約01:00）",
  },
];

export const TYPE_BADGE: Record<string, string> = {
  "府相朝垣格": "bg-jade/10 text-jade border-jade/30",
  "殺破狼格": "bg-vermillion-l text-vermillion border-vermillion/30",
  "火貪格": "bg-gold/10 text-gold border-gold/30",
  "極居卯酉格": "bg-gold/10 text-gold border-gold/30",
  "羊陀夾忌格": "bg-paper-2 text-ink-4 border-border-warm",
};
