// Canonical 命格 (destiny patterns / named formations) in 紫微斗數.
// Each entry drives SEO page generation + RAG retrieval + QA validation.

export interface MinggeEntry {
  slug: string;
  urlSlug: string; // pinyin-friendly URL slug        // used for file key and URL segment
  name: string;        // display name (with 格 suffix where applicable)
  type: "吉格" | "兇格" | "特殊";
  stars: string[];     // key stars involved (for RAG retrieval)
  brief: string;       // one-line definition for meta / intro
  condition: string;   // formation requirement (for prompt grounding)
  topic: string;       // RAG topic tag
}

export const MINGGE_LIST: MinggeEntry[] = [
  // ── 吉格 ────────────────────────────────────────────────────────────────
  {
    slug: "石中隱玉格",
    urlSlug: "shi-zhong-yin-yu",
    name: "石中隱玉格",
    type: "吉格",
    stars: ["巨門","文昌","文曲","天魁","天鉞"],
    brief: "巨門在子午宮坐命，得昌曲魁鉞、祿權科會照而無煞，主才華內斂、大器晚成",
    condition: "巨門坐命子宮或午宮，三方四正有文昌、文曲、天魁、天鉞、化祿/化權/化科會合，無四煞衝破",
    topic: "格局",
  },
  {
    slug: "君臣慶會格",
    urlSlug: "jun-chen-qing-hui",
    name: "君臣慶會格",
    type: "吉格",
    stars: ["紫微","天府","天相","左輔","右弼","文昌","文曲"],
    brief: "紫微在命宮，得天府天相、左輔右弼、昌曲魁鉞全數會照，無煞，主高貴富貴",
    condition: "紫微坐命，三方四正有天府或天相，並得左輔右弼、文昌文曲等百官會合，無煞刑衝破",
    topic: "格局",
  },
  {
    slug: "紫府同宮格",
    urlSlug: "ziwei-fu-tong-gong",
    name: "紫府同宮格",
    type: "吉格",
    stars: ["紫微","天府"],
    brief: "紫微與天府同宮於寅宮或申宮，主尊貴穩重、財官俱佳",
    condition: "紫微與天府同坐命宮寅宮或申宮，或會照三方四正",
    topic: "格局",
  },
  {
    slug: "日月並明格",
    urlSlug: "ri-yue-bing-ming",
    name: "日月並明格",
    type: "吉格",
    stars: ["太陽","太陰"],
    brief: "太陽太陰均處廟旺之地，光華並耀，主文武雙全、名聲顯赫",
    condition: "太陽在卯辰宮以上旺地，太陰在子亥戌宮旺地，雙星同時居於廟旺",
    topic: "格局",
  },
  {
    slug: "機月同梁格",
    urlSlug: "ji-yue-tong-liang",
    name: "機月同梁格",
    type: "吉格",
    stars: ["天機","太陰","天同","天梁"],
    brief: "天機、太陰、天同、天梁四星在命宮或三方四正會合，古訣曰「機月同梁作吏人」，主穩健入仕",
    condition: "天機、太陰、天同、天梁四星在同一三方四正格局內會齊，利公職、輔助性工作",
    topic: "格局",
  },
  {
    slug: "殺破狼格",
    urlSlug: "sha-po-lang",
    name: "殺破狼格",
    type: "吉格",
    stars: ["七殺","破軍","貪狼"],
    brief: "七殺、破軍、貪狼在命宮或遷移宮三方四正會合，主闖蕩冒險、大起大落，非常格",
    condition: "七殺、破軍、貪狼三星以三方四正相會（含坐命），衝突與進取並存",
    topic: "格局",
  },
  {
    slug: "日照雷門格",
    urlSlug: "ri-zhao-lei-men",
    name: "日照雷門格",
    type: "吉格",
    stars: ["太陽"],
    brief: "太陽坐命於卯宮（旺地），如日出東方，光芒普照，主貴顯、名聲廣播",
    condition: "太陽獨坐命宮卯宮（旺地），有祿、昌曲會照更佳，無煞衝破",
    topic: "格局",
  },
  {
    slug: "月朗天門格",
    urlSlug: "yue-lang-tian-men",
    name: "月朗天門格",
    type: "吉格",
    stars: ["太陰"],
    brief: "太陰在亥宮或戌宮旺地坐命，月華皎潔，主溫雅、富貴、利女命",
    condition: "太陰在亥宮（旺/廟）坐命，見吉星會照，無煞刑衝破",
    topic: "格局",
  },
  {
    slug: "火貪格",
    urlSlug: "huo-tan",
    name: "火貪格",
    type: "吉格",
    stars: ["火星","貪狼"],
    brief: "火星與貪狼同宮或三合相會，主意外之財、暴發橫財，一生多變數",
    condition: "火星與貪狼在同宮或三合宮相會（命宮、遷移宮等），得此格主意外貴人與橫發",
    topic: "格局",
  },
  {
    slug: "鈴貪格",
    urlSlug: "ling-tan",
    name: "鈴貪格",
    type: "吉格",
    stars: ["鈴星","貪狼"],
    brief: "鈴星與貪狼同宮或三合相會，與火貪格同類，主橫財突發，但力量稍遜",
    condition: "鈴星與貪狼在同宮或三合宮相會，效果與火貪格類似",
    topic: "格局",
  },
  {
    slug: "財蔭夾印格",
    urlSlug: "cai-yin-jia-yin",
    name: "財蔭夾印格",
    type: "吉格",
    stars: ["祿存","天梁","天相"],
    brief: "祿存或化祿（財）、天梁（蔭）夾天相（印），主財官俱全",
    condition: "天相在命宮，鄰宮一側見祿存或化祿、另一側見天梁夾護",
    topic: "格局",
  },
  {
    slug: "祿馬交馳格",
    urlSlug: "lu-ma-jiao-chi",
    name: "祿馬交馳格",
    type: "吉格",
    stars: ["祿存","天馬"],
    brief: "祿存與天馬同宮或在三方四正相會，財祿流動，主奔波中取財、經商有利",
    condition: "祿存與天馬同宮（最佳）或在命宮遷移宮形成對宮相照，化祿加會更旺",
    topic: "格局",
  },
  {
    slug: "陽梁昌祿格",
    urlSlug: "yang-liang-chang-lu",
    name: "陽梁昌祿格",
    type: "吉格",
    stars: ["太陽","天梁","文昌","祿存"],
    brief: "太陽、天梁、文昌、化祿（或祿存）四者在三方四正會合，主科名仕途、金榜題名",
    condition: "太陽與天梁會照，且有文昌與化祿（或祿存）同宮或會入三方四正",
    topic: "格局",
  },
  {
    slug: "府相朝垣格",
    urlSlug: "fu-xiang-zhao-yuan",
    name: "府相朝垣格",
    type: "吉格",
    stars: ["天府","天相","紫微"],
    brief: "天府天相在三方四正拱照紫微或命宮，主穩重貴氣、財官雙全",
    condition: "天府、天相在三方四正會合，形成對紫微或命宮的拱護之勢",
    topic: "格局",
  },
  {
    slug: "三奇加會格",
    urlSlug: "san-qi-jia-hui",
    name: "三奇加會格",
    type: "吉格",
    stars: ["化祿","化權","化科"],
    brief: "化祿、化權、化科三顆吉化星同時在命宮三方四正會合，主功成名就",
    condition: "化祿、化權、化科三者同時匯入命宮三方四正，無化忌衝破更佳",
    topic: "格局",
  },
  {
    slug: "貪武同行格",
    urlSlug: "tan-wu-tong-xing",
    name: "貪武同行格",
    type: "吉格",
    stars: ["貪狼","武曲"],
    brief: "貪狼與武曲同宮於醜宮或未宮，財藝並重，主商界或藝能界得財",
    condition: "貪狼與武曲同坐醜宮或未宮，或在三方四正相會",
    topic: "格局",
  },
  {
    slug: "馬頭帶箭格",
    urlSlug: "ma-tou-dai-jian",
    name: "馬頭帶箭格",
    type: "吉格",
    stars: ["擎羊","天馬"],
    brief: "擎羊在午宮坐命或事業宮，天馬同臨，主武職軍警、果敢決斷",
    condition: "擎羊在午宮（陷地反成特殊格局），與天馬同宮或命宮在此，適合武職",
    topic: "格局",
  },
  {
    slug: "七殺朝鬥格",
    urlSlug: "qi-sha-zhao-dou",
    name: "七殺朝鬥格",
    type: "吉格",
    stars: ["七殺"],
    brief: "七殺在子宮或午宮坐命，朝向北極（紫微），主威權領導、軍政要職",
    condition: "七殺在子宮或午宮獨坐命宮，無煞刑衝破，有祿、左右會照更佳",
    topic: "格局",
  },
  {
    slug: "百官朝拱格",
    urlSlug: "bai-guan-zhao-gong",
    name: "百官朝拱格",
    type: "吉格",
    stars: ["紫微","左輔","右弼","文昌","文曲","天魁","天鉞"],
    brief: "紫微在命宮，左輔右弼、文昌文曲、天魁天鉞等輔星全數會合，主尊貴至極",
    condition: "紫微坐命，三方四正有左輔、右弼、文昌、文曲、天魁、天鉞多星拱照",
    topic: "格局",
  },

  // ── 兇格 ────────────────────────────────────────────────────────────────
  {
    slug: "鈴昌陀武格",
    urlSlug: "ling-chang-tuo-wu",
    name: "鈴昌陀武格",
    type: "兇格",
    stars: ["鈴星","文昌","陀羅","武曲"],
    brief: "鈴星、文昌、陀羅、武曲在三方四正相會，主刑剋破財、內耗頻發",
    condition: "鈴星與文昌同宮或三合，陀羅與武曲同宮或三合，四星交會於三方四正",
    topic: "格局",
  },
  {
    slug: "風流彩杖格",
    urlSlug: "feng-liu-cai-zhang",
    name: "風流彩杖格",
    type: "兇格",
    stars: ["貪狼","擎羊"],
    brief: "貪狼與擎羊同宮，桃花星與煞星並立，主好色招禍、因情生災",
    condition: "貪狼與擎羊同宮於命宮或夫妻宮，主感情糾紛或法律糾紛",
    topic: "格局",
  },
  {
    slug: "刑囚夾印格",
    urlSlug: "xing-qiu-jia-yin",
    name: "刑囚夾印格",
    type: "兇格",
    stars: ["廉貞","天相","擎羊"],
    brief: "廉貞（刑）與天相（印）同坐命宮，擎羊同宮或夾宮，主官司訴訟、囹圄之患",
    condition: "廉貞、天相同坐命宮（僅寅、申二宮成立），擎羊同宮或在鄰宮夾住",
    topic: "格局",
  },
  {
    slug: "日月反背格",
    urlSlug: "ri-yue-fan-bei",
    name: "日月反背格",
    type: "兇格",
    stars: ["太陽","太陰"],
    brief: "太陽在酉宮（落陷）、太陰在卯宮（落陷），日月各自背光，主早年勞苦、父母緣薄",
    condition: "太陽在酉宮落陷，太陰在卯宮落陷，雙星同時處於失陷之地",
    topic: "格局",
  },
  {
    slug: "命無正曜格",
    urlSlug: "ming-wu-zheng-yao",
    name: "命無正曜格",
    type: "兇格",
    stars: [],
    brief: "命宮無十四主星坐守，借對宮或三方四正之星論命，主六親緣薄、個性獨特",
    condition: "命宮無任何十四正曜落宮，須看對宮（遷移宮）及三方四正諸星來論命",
    topic: "格局",
  },
  {
    slug: "日月照壁格",
    urlSlug: "ri-yue-zhao-bi",
    name: "日月照壁格",
    type: "兇格",
    stars: ["太陽","太陰"],
    brief: "太陽與太陰互相對照，各在落陷位，光芒受阻，主事業受挫、名譽有損",
    condition: "太陽在申酉宮，太陰在卯辰宮，日月光芒各自折射、受壁阻遮",
    topic: "格局",
  },
  {
    slug: "極居卯酉格",
    urlSlug: "ji-ju-mao-you",
    name: "極居卯酉格",
    type: "兇格",
    stars: ["紫微"],
    brief: "紫微在卯宮或酉宮坐命，帝星失輔，主孤傲多阻，須吉星救助方可化解",
    condition: "紫微獨坐命宮於卯宮或酉宮，無左輔右弼、昌曲輔佐，煞忌加重更兇",
    topic: "格局",
  },
  {
    slug: "羊陀夾忌格",
    urlSlug: "yang-tuo-jia-ji",
    name: "羊陀夾忌格",
    type: "兇格",
    stars: ["擎羊","陀羅","化忌"],
    brief: "擎羊與陀羅夾住化忌所在宮位，煞忌交攻，主該宮所代表的人事受重創",
    condition: "化忌所在宮位，左側（前一宮）為擎羊，右側（後一宮）為陀羅，形成夾擊",
    topic: "格局",
  },
  {
    slug: "火鈴夾命格",
    urlSlug: "huo-ling-jia-ming",
    name: "火鈴夾命格",
    type: "兇格",
    stars: ["火星","鈴星"],
    brief: "火星與鈴星分別在命宮兩側夾住命宮，主性情暴烈、多意外兇險",
    condition: "命宮左右兩側各有火星和鈴星夾住（前一宮後一宮），無吉星解救則兇",
    topic: "格局",
  },

  // ── 特殊格局 ─────────────────────────────────────────────────────────────
  {
    slug: "明珠出海格",
    urlSlug: "ming-zhu-chu-hai",
    name: "明珠出海格",
    type: "特殊",
    stars: ["太陰"],
    brief: "太陰在子宮或亥宮旺地坐命，月華流光，主才華顯露、異途成名",
    condition: "太陰在子宮（旺）或亥宮（旺）坐命，得昌曲或祿會照，無煞衝破",
    topic: "格局",
  },
  {
    slug: "極向離明格",
    urlSlug: "ji-xiang-li-ming",
    name: "極向離明格",
    type: "特殊",
    stars: ["紫微"],
    brief: "紫微在午宮坐命，帝星向南方離火之位，主剛斷英明、事業成就高",
    condition: "紫微在午宮獨坐命宮，無煞衝破，有左右昌曲會照則格局更高",
    topic: "格局",
  },
  {
    slug: "丹墀桂墀格",
    urlSlug: "dan-chi-gui-chi",
    name: "丹墀桂墀格",
    type: "特殊",
    stars: ["文昌","文曲"],
    brief: "文昌文曲同宮坐命，或分居命宮兩側夾命，主文秀聰慧、利科甲考試",
    condition: "文昌與文曲同宮坐命，或分別在命宮前後宮位夾住命宮，學術藝文方面有成",
    topic: "格局",
  },
];

// For RAG retrieval in seoContent — pull all unique star names from a 命格 entry
export function minggeGroundingBlock(entry: MinggeEntry): string {
  return `【命格名稱】${entry.name}
【格局型別】${entry.type}
【核心要義】${entry.brief}
【入格條件】${entry.condition}
【涉及主要星曜】${entry.stars.length ? entry.stars.join("、") : "無固定主星（看整體格局）"}`;
}
