// Corpus source books — all books in knowledge/extracted/ that contribute to the RAG
// Displayed at /sources (hub) and /sources/[slug] (individual articles)

export type SourceSchool =
  | "三合派"
  | "四化派"
  | "飛星派"
  | "倪師學派"
  | "八字命理"
  | "八字祿命"
  | "八字盲派"
  | "古籍經典"
  | "其他名家";

export interface SourceBook {
  slug: string;       // Chinese display slug (matches content/seo/sources/[slug].json)
  urlSlug: string;    // URL-safe pinyin slug
  title: string;      // Display title (clean, no author prefix)
  author: string;     // Author(s) — empty string if unknown
  school: SourceSchool;
  era: "古代" | "近現代" | "當代";
  chunks: number;     // Approximate corpus chunk count
  tags: string[];     // Key topics covered
  intro: string;      // One-line description for the hub page list
}

export const SOURCE_BOOKS: SourceBook[] = [
  // ── 三合派 ─────────────────────────────────────────────────────────────────
  {
    slug: "王亭之-中州派初級講義",
    urlSlug: "wangtingzhi-zhongzhou-jichu",
    title: "中州派紫微斗數初級講義",
    author: "王亭之",
    school: "三合派",
    era: "當代",
    chunks: 257,
    tags: ["三合派", "中州派", "宮氣論", "星曜斷命", "初級"],
    intro: "香港三合派宗師王亭之親授初級系統講義，奠定中州派宮氣論斷命體系的入門基礎。",
  },
  {
    slug: "王亭之-中州派深造講義(下)",
    urlSlug: "wangtingzhi-zhongzhou-shenzao",
    title: "中州派紫微斗數深造講義（下）",
    author: "王亭之",
    school: "三合派",
    era: "當代",
    chunks: 299,
    tags: ["三合派", "中州派", "宮垣", "格局", "深造"],
    intro: "中州派深造課程下篇，專論宮垣關係與高階格局推斷，是三合派進階核心典籍。",
  },
  {
    slug: "王亭之談紫微斗數",
    urlSlug: "wangtingzhi-tan-ziwei",
    title: "王亭之談紫微斗數",
    author: "王亭之",
    school: "三合派",
    era: "當代",
    chunks: 127,
    tags: ["三合派", "星曜性質", "命盤解析", "心法"],
    intro: "王亭之以問答與案例形式闡述三合派論命心法，語言平實，實用性強。",
  },
  {
    slug: "陸斌兆+王亭之-星曜性質講義",
    urlSlug: "lubinzhao-wangtingzhi-xingyao",
    title: "星曜性質講義",
    author: "陸斌兆、王亭之",
    school: "三合派",
    era: "當代",
    chunks: 179,
    tags: ["三合派", "星曜", "性質", "宮位應用"],
    intro: "陸斌兆與王亭之合著，系統梳理各主星輔星性質，是三合派星曜研究的權威參考。",
  },
  {
    slug: "王亭之-紫微斗數全集(一)",
    urlSlug: "wangtingzhi-quanji-yi",
    title: "紫微斗數全集（一）",
    author: "王亭之",
    school: "三合派",
    era: "當代",
    chunks: 14,
    tags: ["三合派", "全集", "綜合"],
    intro: "王亭之紫微斗數全集第一冊，涵蓋三合派總論與基礎命理原理。",
  },
  {
    slug: "王亭之-紫微斗數全集流年兇災詳析",
    urlSlug: "wangtingzhi-liunian-xiongzai",
    title: "紫微斗數全集·流年兇災詳析",
    author: "王亭之",
    school: "三合派",
    era: "當代",
    chunks: 27,
    tags: ["三合派", "流年", "兇災", "煞星"],
    intro: "專論流年兇災的判斷方法，詳述各類煞星組合在流年中引發意外的推斷邏輯。",
  },

  // ── 倪師學派 ───────────────────────────────────────────────────────────────
  {
    slug: "天紀-人間道",
    urlSlug: "tianji-renjiandao",
    title: "天紀·人間道",
    author: "倪海廈",
    school: "倪師學派",
    era: "當代",
    chunks: 130,
    tags: ["倪師學派", "人間道", "紫微斗數", "命運哲學"],
    intro: "倪海廈天紀系列核心卷，以紫微斗數為綱，貫通天地人三才，是倪師命理哲學的集中呈現。",
  },
  {
    slug: "天紀-地脈道(文字版)",
    urlSlug: "tianji-dimaodao",
    title: "天紀·地脈道",
    author: "倪海廈",
    school: "倪師學派",
    era: "當代",
    chunks: 46,
    tags: ["倪師學派", "地脈道", "風水", "地理"],
    intro: "天紀系列地脈道，論述地理風水與人命的關聯，是倪師完整命理體系的組成部分。",
  },
  {
    slug: "天紀-天機道(簡體版)",
    urlSlug: "tianji-tianjidao",
    title: "天紀·天機道",
    author: "倪海廈",
    school: "倪師學派",
    era: "當代",
    chunks: 80,
    tags: ["倪師學派", "天機道", "天時", "命理總論"],
    intro: "天紀系列天機道，闡述天時節氣對命盤的影響及推運的原理，體系最為系統。",
  },
  {
    slug: "天紀-易經",
    urlSlug: "tianji-yijing",
    title: "天紀·易經",
    author: "倪海廈",
    school: "倪師學派",
    era: "當代",
    chunks: 432,
    tags: ["倪師學派", "易經", "六十四卦", "哲學基礎"],
    intro: "倪海廈講授易經全本，是理解倪師命理體系哲學根基的必讀之作。",
  },
  {
    slug: "天紀學習筆記",
    urlSlug: "tianji-xuexi-biji",
    title: "天紀學習筆記",
    author: "倪海廈學員整理",
    school: "倪師學派",
    era: "當代",
    chunks: 48,
    tags: ["倪師學派", "天紀", "筆記", "整理"],
    intro: "學員系統整理的天紀課程筆記，涵蓋紫微斗數與命理總論的核心要點。",
  },

  // ── 四化派 ─────────────────────────────────────────────────────────────────
  {
    slug: "翁福裕-欽天無極門飛星四化",
    urlSlug: "wengfuyu-qintian-sihua",
    title: "欽天無極門大易源正宗紫微斗數飛星四化",
    author: "翁福裕、李子陽",
    school: "四化派",
    era: "當代",
    chunks: 205,
    tags: ["四化派", "欽天四化", "飛星", "飛化體系"],
    intro: "欽天無極門正宗四化心法，系統闡述飛化體系的推命原理，是四化派高階典籍。",
  },
  {
    slug: "蔡明宏-紫微斗數悟我十八年",
    urlSlug: "caiminhong-wuwo-shiba",
    title: "紫微斗數悟我十八年",
    author: "蔡明宏",
    school: "四化派",
    era: "當代",
    chunks: 304,
    tags: ["四化派", "華山派", "欽天四化", "實戰心得"],
    intro: "蔡明宏十八年紫微斗數研究心得，結合華山派與欽天四化，實案豐富，論斷細膩。",
  },
  {
    slug: "許銓仁-高階班課程筆記",
    urlSlug: "xuquanren-gaoji-biji",
    title: "欽天四化紫微斗數高階班課程筆記",
    author: "許銓仁",
    school: "四化派",
    era: "當代",
    chunks: 83,
    tags: ["四化派", "欽天四化", "高階", "飛化"],
    intro: "許銓仁高階班系統講授飛星四化的進階用法，涵蓋化忌飛化與三方四正的深度應用。",
  },
  {
    slug: "許銓仁-高階課程整理版",
    urlSlug: "xuquanren-gaoji-zhengli",
    title: "欽天四化高階課程整理版",
    author: "許銓仁",
    school: "四化派",
    era: "當代",
    chunks: 70,
    tags: ["四化派", "高階", "整理版"],
    intro: "許銓仁高階課程系統整理，以結構化方式呈現四化飛化的高階推命體系。",
  },
  {
    slug: "許銓仁-24集影片筆記",
    urlSlug: "xuquanren-24ji-biji",
    title: "欽天四化紫微斗數基礎講義（24集）",
    author: "許銓仁",
    school: "四化派",
    era: "當代",
    chunks: 60,
    tags: ["四化派", "基礎", "宮位", "星辰"],
    intro: "許銓仁24集基礎課程完整講義，系統介紹四化派宮位邏輯與星辰象意。",
  },
  {
    slug: "黃天福-欽天四化中級班筆記",
    urlSlug: "huangtianfu-zhongji-biji",
    title: "欽天四化紫微斗數中級班筆記",
    author: "黃天福",
    school: "四化派",
    era: "當代",
    chunks: 54,
    tags: ["四化派", "中級", "欽天四化"],
    intro: "黃天福中級班系統講授四化體系中層推命技法，銜接基礎與高階，實用清晰。",
  },

  // ── 飛星派 ─────────────────────────────────────────────────────────────────
  {
    slug: "中國神秘文化通鑑-飛星紫微斗數",
    urlSlug: "feixing-shenmi-wenhua",
    title: "飛星紫微斗數（中國神秘文化通鑑版）",
    author: "中州古籍出版社整理",
    school: "飛星派",
    era: "近現代",
    chunks: 194,
    tags: ["飛星派", "正統飛星", "古籍整理"],
    intro: "中州古籍出版社整理版飛星紫微斗數，保留正統飛星體系，是飛星派重要文獻。",
  },
  {
    slug: "梁若瑜-生命解碼飛星盤版文字",
    urlSlug: "lianggruoyu-shengming-jiemai",
    title: "生命解碼·飛星盤版",
    author: "梁若瑜",
    school: "飛星派",
    era: "當代",
    chunks: 186,
    tags: ["飛星派", "生命解碼", "四化論命", "實案"],
    intro: "梁若瑜系統整理飛星派四化論命精髓，以生命解碼為框架呈現，實案豐富。",
  },
  {
    slug: "飛星紫微斗數(佚名)",
    urlSlug: "feixing-ziwei-yiming",
    title: "飛星紫微斗數（佚名）",
    author: "佚名",
    school: "飛星派",
    era: "近現代",
    chunks: 193,
    tags: ["飛星派", "飛星推命", "傳統"],
    intro: "飛星派傳統推命典籍，保留四化飛化的核心原理，作者不詳，內容完整系統。",
  },
  {
    slug: "飛星派-幼兒園班課程",
    urlSlug: "feixing-youeryuan",
    title: "飛星紫微斗數幼兒園班課程",
    author: "梁若瑜系學員整理",
    school: "飛星派",
    era: "當代",
    chunks: 150,
    tags: ["飛星派", "入門", "基礎", "幼兒園班"],
    intro: "飛星派體系化入門課程，以最平易的方式講解四化體系基礎，適合零基礎學員。",
  },
  {
    slug: "梁若瑜-十二宮六七二象",
    urlSlug: "lianggruoyu-shier-gong",
    title: "十二宮六七二象",
    author: "梁若瑜",
    school: "飛星派",
    era: "當代",
    chunks: 111,
    tags: ["飛星派", "十二宮", "星象", "六象七象"],
    intro: "梁若瑜詳論十二宮星象組合，六七二象體系是飛星派獨特的斷命邏輯精華。",
  },
  {
    slug: "梁若瑜-飛星紫微斗數入門篇",
    urlSlug: "lianggruoyu-feixing-rumen",
    title: "飛星紫微斗數入門篇",
    author: "梁若瑜",
    school: "飛星派",
    era: "當代",
    chunks: 135,
    tags: ["飛星派", "入門", "星曜釋義", "四化"],
    intro: "梁若瑜飛星派入門教材，系統介紹星曜象意與四化基礎邏輯，是飛星派入門首選。",
  },
  {
    slug: "白派飛宮-速成體系A卷",
    urlSlug: "baipai-feigong-sucheung",
    title: "白派飛宮速成體系（A卷基礎篇）",
    author: "白派飛宮",
    school: "飛星派",
    era: "當代",
    chunks: 90,
    tags: ["飛星派", "白派", "飛宮", "速成"],
    intro: "白派飛宮獨特速成體系A卷，以簡潔框架快速上手飛宮推命，自成一格。",
  },
  {
    slug: "顧祥弘-飛星紫微斗數全書",
    urlSlug: "guxianghong-feixing-quanshu",
    title: "飛星紫微斗數全書",
    author: "顧祥弘",
    school: "飛星派",
    era: "當代",
    chunks: 30,
    tags: ["飛星派", "全書", "體系"],
    intro: "顧祥弘系統整理飛星派推命全書，涵蓋飛化體系的完整推命框架。",
  },

  // ── 八字命理（子平） ────────────────────────────────────────────────────────
  {
    slug: "萬民英-三命通會",
    urlSlug: "wanminying-sanming-tonghui",
    title: "三命通會",
    author: "萬民英",
    school: "八字命理",
    era: "古代",
    chunks: 535,
    tags: ["八字", "子平", "格局", "古籍", "三命"],
    intro: "明代萬民英所著，八字命理最系統的綜合性古籍，是子平法最重要的歷史文獻之一。",
  },
  {
    slug: "餘春臺-窮通寶鑑",
    urlSlug: "yuchuntai-qiongtong-baojian",
    title: "窮通寶鑑",
    author: "餘春臺整理",
    school: "八字命理",
    era: "古代",
    chunks: 295,
    tags: ["八字", "調候用神", "月令", "季節"],
    intro: "清代調候用神專著，按月令逐日干論命，是判斷日主喜忌的核心參考典籍。",
  },
  {
    slug: "徐子平-淵海子平",
    urlSlug: "xuzipping-yuanhai-ziping",
    title: "淵海子平",
    author: "徐子平（宋）",
    school: "八字命理",
    era: "古代",
    chunks: 621,
    tags: ["八字", "子平", "十神", "格局", "古籍"],
    intro: "宋代徐子平所創子平法的奠基性典籍，八字命理完整體系的最早系統著述。",
  },
  {
    slug: "張楠-神峰通考",
    urlSlug: "zhangnan-shenfeng-tongkao",
    title: "神峰通考",
    author: "張楠",
    school: "八字命理",
    era: "古代",
    chunks: 252,
    tags: ["八字", "格局", "神煞", "案例"],
    intro: "明代張楠（神峰子）著，融格局與神煞為一體，含大量歷史名人命例，實用價值極高。",
  },
  {
    slug: "子平正解",
    urlSlug: "ziping-zhengjie",
    title: "子平正解",
    author: "徐傳剛",
    school: "八字命理",
    era: "當代",
    chunks: 403,
    tags: ["八字", "子平", "格局", "正解", "現代"],
    intro: "現代子平命理系統梳理，以嚴謹學術態度重新詮釋子平格局體系，條理清晰。",
  },
  {
    slug: "沈孝瞻-子平真詮",
    urlSlug: "shenxiaozhan-ziping-zhengquan",
    title: "子平真詮",
    author: "沈孝瞻（清）",
    school: "八字命理",
    era: "古代",
    chunks: 42,
    tags: ["八字", "子平", "格局", "真詮", "清代"],
    intro: "清代子平格局論命最權威著作，以月令為核心論取格局，是格局派必讀經典。",
  },
  {
    slug: "韋千里-千里命稿",
    urlSlug: "weiqianli-qianli-minggao",
    title: "千里命稿",
    author: "韋千里",
    school: "八字命理",
    era: "近現代",
    chunks: 167,
    tags: ["八字", "現代", "案例", "實戰", "韋千里"],
    intro: "民國命理大師韋千里的實戰命稿，案例詳盡，論命方法兼收並蓄，是近現代八字實用典範。",
  },
  {
    slug: "梁湘潤-命理傳承班筆記",
    urlSlug: "liangxiangrun-chuancheng-biji",
    title: "梁湘潤命理傳承班筆記",
    author: "梁湘潤",
    school: "八字命理",
    era: "當代",
    chunks: 243,
    tags: ["八字", "臺灣", "格局", "傳承"],
    intro: "臺灣命理大家梁湘潤傳承班課程精華筆記，深入淺出地整合子平體系核心推命邏輯。",
  },
  {
    slug: "梁湘潤-子平基礎概要",
    urlSlug: "liangxiangrun-jichu-gaiyao",
    title: "子平基礎概要",
    author: "梁湘潤",
    school: "八字命理",
    era: "當代",
    chunks: 226,
    tags: ["八字", "子平", "基礎", "臺灣"],
    intro: "梁湘潤子平基礎體系完整論述，系統覆蓋天干地支、格局取用到大運流年，是入門基礎典籍。",
  },
  {
    slug: "陳國日-命理金鑑",
    urlSlug: "chenguori-mingli-jinjian",
    title: "命理金鑑",
    author: "陳國日",
    school: "八字命理",
    era: "當代",
    chunks: 135,
    tags: ["八字", "現代", "金鑑", "綜合"],
    intro: "陳國日綜合子平命理精華，以\"金鑑\"為名，博採各家之長，適合進階學習參考。",
  },
  {
    slug: "潘東光-八字批論選集",
    urlSlug: "pandongguang-bazi-pilun",
    title: "八字批論選集",
    author: "潘東光",
    school: "八字命理",
    era: "當代",
    chunks: 82,
    tags: ["八字", "批命例項", "實戰", "案例"],
    intro: "潘東光精選批命例項彙編，以真實案例逐步解析八字論斷邏輯，是實戰學習的優質範本。",
  },
  {
    slug: "邵偉華-四柱預測學入門",
    urlSlug: "shaoweigua-sizhu-rumen",
    title: "四柱預測學入門",
    author: "邵偉華",
    school: "八字命理",
    era: "當代",
    chunks: 168,
    tags: ["八字", "四柱", "預測", "入門", "大陸版"],
    intro: "邵偉華四柱預測學入門教材，以通俗語言系統講解四柱八字，是大陸最廣泛流傳的入門書之一。",
  },
  {
    slug: "黃勇智-八字讀象預測法",
    urlSlug: "huangyongzhi-bazi-duxiang",
    title: "八字讀象預測法",
    author: "黃勇智",
    school: "八字命理",
    era: "當代",
    chunks: 137,
    tags: ["八字", "讀象", "意象", "現代"],
    intro: "黃勇智以\"讀象\"為核心論述八字預測，重視意象直讀，不拘泥格局框架。",
  },
  {
    slug: "翁向宏-子平八字命理學術",
    urlSlug: "wengxianghong-ziping-xueshu",
    title: "子平八字命理學術",
    author: "翁向宏",
    school: "八字命理",
    era: "當代",
    chunks: 41,
    tags: ["八字", "子平", "學術", "系統"],
    intro: "翁向宏以學術視角系統整理子平八字命理，論斷有據，結構清晰。",
  },
  {
    slug: "蔡昔瓊-四柱函授資料",
    urlSlug: "caixiqiong-sizhu-hanhsou",
    title: "四柱函授資料",
    author: "蔡昔瓊",
    school: "八字命理",
    era: "近現代",
    chunks: 65,
    tags: ["八字", "四柱", "函授", "傳統"],
    intro: "蔡昔瓊函授課程資料，系統傳授傳統四柱推命方法，含格局、神煞與大運推斷。",
  },
  {
    slug: "李虛中-命書",
    urlSlug: "lixuzhong-mingshu",
    title: "李虛中命書",
    author: "李虛中（唐）、鬼谷子",
    school: "八字命理",
    era: "古代",
    chunks: 44,
    tags: ["八字", "唐代", "早期子平", "納音"],
    intro: "唐代李虛中所著，是中國命理史上最早系統化的命書，以納音五行論命，為子平法前身。",
  },
  {
    slug: "命理探源",
    urlSlug: "mingli-tanyuan",
    title: "命理探源",
    author: "袁樹珊（清）",
    school: "八字命理",
    era: "古代",
    chunks: 85,
    tags: ["八字", "探源", "清代", "綜合"],
    intro: "清代袁樹珊所著，梳理命理各家源流，匯通五行、干支與格局之說，是研究命理史的重要文獻。",
  },
  {
    slug: "四柱詳批命例精解",
    urlSlug: "sizhu-xiangpi-mingli",
    title: "四柱詳批命例精解",
    author: "佚名",
    school: "八字命理",
    era: "當代",
    chunks: 154,
    tags: ["八字", "例項", "詳批", "精解"],
    intro: "精選典型命例進行系統詳批，從排盤到大運流年逐步論斷，是實戰案例學習的優質資源。",
  },
  {
    slug: "八字例項詳解",
    urlSlug: "bazi-shili-xiangjie",
    title: "八字例項詳解",
    author: "佚名",
    school: "八字命理",
    era: "當代",
    chunks: 67,
    tags: ["八字", "例項", "詳解", "案例"],
    intro: "以豐富的實際命例為材料，逐步拆解八字論斷過程，適合對照學習。",
  },
  {
    slug: "學易堂-八字神煞大全",
    urlSlug: "xueyitang-bazi-shenzha",
    title: "八字神煞大全",
    author: "學易堂（易樸）",
    school: "八字命理",
    era: "當代",
    chunks: 15,
    tags: ["八字", "神煞", "大全"],
    intro: "系統收錄八字命理中的神煞體系，分類清晰，是查閱各類神煞定義與作用的實用工具書。",
  },
  {
    slug: "黃鑑-中華人與時空學",
    urlSlug: "huangjian-zhonghua-shikong",
    title: "中華人與時空學",
    author: "黃鑑",
    school: "八字命理",
    era: "當代",
    chunks: 304,
    tags: ["八字", "時空學", "現代", "綜合"],
    intro: "黃鑑以\"人與時空\"為框架重構八字命理體系，融合現代視角與傳統理論，體系新穎。",
  },
  {
    slug: "李洪成-古今四柱6000例簡析",
    urlSlug: "lihongcheng-gujin-sizhu-6000li",
    title: "古今四柱6000例簡析·丙丁年生命造",
    author: "李洪成",
    school: "八字命理",
    era: "當代",
    chunks: 522,
    tags: ["八字", "例項", "四柱", "案例", "命造"],
    intro: "李洪成整理的大型八字例項集，收錄古今丙丁年出生命造逾千例，以簡析格式呈現，是八字斷命的實戰參考。",
  },

  // ── 八字祿命 ────────────────────────────────────────────────────────────────
  {
    slug: "祿命法入門到精通",
    urlSlug: "luming-rumen-jingtong",
    title: "祿命法：從入門到精通",
    author: "佚名",
    school: "八字祿命",
    era: "當代",
    chunks: 317,
    tags: ["祿命法", "納音五行", "神煞", "祿命"],
    intro: "目前最系統的祿命法入門與進階教材，從納音五行到神煞應用，是研究祿命法體系的核心文獻。",
  },
  {
    slug: "玉照定真經",
    urlSlug: "yuzhao-dingzhenjing",
    title: "玉照定真經",
    author: "佚名（宋）",
    school: "八字祿命",
    era: "古代",
    chunks: 32,
    tags: ["祿命法", "古籍", "玉照", "神煞", "宋代"],
    intro: "宋代祿命法古籍，以\"玉照\"為喻論述神煞與五行的應用，是祿命法最重要的古代文獻之一。",
  },
  {
    slug: "人鑑命理存驗五十例",
    urlSlug: "renjian-cunyan-wushili",
    title: "人鑑·命理存驗五十例（後附六十七例）",
    author: "林庚白（民國）",
    school: "八字祿命",
    era: "近現代",
    chunks: 63,
    tags: ["祿命法", "命例", "民國", "人鑑"],
    intro: "民國命理學家林庚白所著《人鑑》命理存驗案例集，以實際命例驗證傳統命理的準確性。",
  },
  {
    slug: "人鑒命理存驗",
    urlSlug: "renjian-cunyan",
    title: "人鑑·命理存驗",
    author: "林庚白（民國）",
    school: "八字祿命",
    era: "近現代",
    chunks: 25,
    tags: ["祿命法", "命例", "民國", "人鑑"],
    intro: "林庚白《人鑑》原本命理存驗部分，記錄祿命法視角下的真實命例推斷過程。",
  },

  // ── 八字盲派 ────────────────────────────────────────────────────────────────
  {
    slug: "清娟盲派八字命理",
    urlSlug: "qingjuan-mangpai-bazi",
    title: "清娟盲派八字命理·理論篇",
    author: "楊老師（清娟命理）",
    school: "八字盲派",
    era: "當代",
    chunks: 23,
    tags: ["盲派", "清娟", "意象", "直斷"],
    intro: "清娟命理盲派義理班核心講義，以直斷意象為特色，不依賴命書印證，自成風格。",
  },
  {
    slug: "乘馬班如-盲派命理學歷篇",
    urlSlug: "chengmabanru-mangpai-xuelipian",
    title: "盲派命理·學歷篇",
    author: "乘馬班如",
    school: "八字盲派",
    era: "當代",
    chunks: 35,
    tags: ["盲派", "乘馬班如", "學歷", "培訓"],
    intro: "盲派命理培訓內部資料學歷篇，系統介紹盲派命理推斷方法，適合深入瞭解盲派體系。",
  },

  // ── 古籍經典 ───────────────────────────────────────────────────────────────
  {
    slug: "紫微斗數-道藏本(ctext)",
    urlSlug: "ziwei-daozangben",
    title: "紫微斗數（道藏本）",
    author: "陳摶（傳）",
    school: "古籍經典",
    era: "古代",
    chunks: 51,
    tags: ["古籍", "道藏", "陳摶", "原典"],
    intro: "收錄於明代正統道藏的紫微斗數最早文本，傳為陳摶所創，是研究斗數源流的第一手文獻。",
  },
  {
    slug: "蘭臺妙選",
    urlSlug: "lantai-miaoxuan",
    title: "蘭臺妙選",
    author: "西窗老人（明）",
    school: "古籍經典",
    era: "古代",
    chunks: 35,
    tags: ["古籍", "明代", "格局", "命理"],
    intro: "明代命理古籍《蘭臺妙選》，記載格局推命要訣，是研究明代命理學的珍貴文獻。",
  },
  {
    slug: "南北山人-紫微斗數全書(明版今注)",
    urlSlug: "nanbei-shanren-quanshu-jinzhu",
    title: "紫微斗數全書（明版今注）",
    author: "南北山人（明）注",
    school: "古籍經典",
    era: "古代",
    chunks: 19,
    tags: ["古籍", "明代", "紫微", "註釋"],
    intro: "明版紫微斗數全書現代註釋本，保留古籍原文並加今注，有助理解斗數原典的歷史語境。",
  },
  {
    slug: "潘國森-紫微斗數全書古訣辨正",
    urlSlug: "panguosen-guojue-bianzheng",
    title: "紫微斗數全書古訣辨正",
    author: "潘國森",
    school: "古籍經典",
    era: "當代",
    chunks: 11,
    tags: ["古籍", "古訣", "辨正", "考證"],
    intro: "潘國森對《紫微斗數全書》古訣的系統考證與辨正，指出古籍中訛傳之處，學術價值高。",
  },

  // ── 其他名家 ───────────────────────────────────────────────────────────────
  {
    slug: "令東來-紫微斗數大全",
    urlSlug: "lingdonglai-ziwei-daquan",
    title: "紫微斗數大全",
    author: "令東來",
    school: "其他名家",
    era: "當代",
    chunks: 504,
    tags: ["其他名家", "令東來", "綜合", "大全"],
    intro: "令東來綜合各派紫微斗數之大成，內容最為全面，是當代紫微斗數體系化綜合的代表作。",
  },
  {
    slug: "令東來-紫微斗數全書(2018更新目錄)",
    urlSlug: "lingdonglai-ziwei-quanshu-2018",
    title: "紫微斗數全書（2018版）",
    author: "令東來",
    school: "其他名家",
    era: "當代",
    chunks: 224,
    tags: ["其他名家", "令東來", "全書", "2018"],
    intro: "令東來2018年更新版紫微斗數全書，修訂補充了較早版本，是最新版綜合參考文獻。",
  },
  {
    slug: "周德元-命理天機-紫微斗數規則",
    urlSlug: "zhoudeyuan-tianji-guize",
    title: "命理天機·紫微斗數規則",
    author: "周德元",
    school: "其他名家",
    era: "當代",
    chunks: 843,
    tags: ["其他名家", "規則體系", "綜合", "全面"],
    intro: "周德元系統整理紫微斗數推命規則，以體系化、結構化方式呈現，是規模最大的綜合性著作之一。",
  },
  {
    slug: "朱雲山-南北派斷訣",
    urlSlug: "zhuyunshan-nanbei-duanjue",
    title: "南北派斷訣",
    author: "朱雲山",
    school: "其他名家",
    era: "當代",
    chunks: 166,
    tags: ["其他名家", "南派", "北派", "斷訣", "對比"],
    intro: "朱雲山比較南北兩派推命斷訣，釐清各家斷命規則的異同，適合有基礎者深入研究。",
  },
  {
    slug: "劉金府-象數心學紫微斗數札記",
    urlSlug: "liujinfu-xiangshu-xinxue",
    title: "象數心學紫微斗數札記",
    author: "劉金府",
    school: "其他名家",
    era: "當代",
    chunks: 192,
    tags: ["其他名家", "象數", "心學", "現代視角"],
    intro: "劉金府以象數心學為框架重新審視紫微斗數，融合現代心理學視角，風格獨特。",
  },
  {
    slug: "紫微斗數命理學(2019最新版)",
    urlSlug: "ziwei-minglixue-2019",
    title: "紫微斗數命理學（2019最新版）",
    author: "令東來",
    school: "其他名家",
    era: "當代",
    chunks: 496,
    tags: ["其他名家", "令東來", "綜合", "命理學"],
    intro: "令東來2019年修訂版命理學綜論，內容最為完整，是當代綜合命理知識的系統化文本。",
  },
  {
    slug: "紫微斗數命理學正解(再版精糾)",
    urlSlug: "ziwei-minglixue-zhengjie",
    title: "紫微斗數命理學正解（再版精糾）",
    author: "佚名",
    school: "其他名家",
    era: "當代",
    chunks: 163,
    tags: ["其他名家", "正解", "精糾", "系統"],
    intro: "經過精糾再版的紫微斗數命理學正解，糾正了早期版本的錯誤，體系完整嚴謹。",
  },
  {
    slug: "周清河-婚姻疾病財帛",
    urlSlug: "zhouqinghe-hunyin-jibing",
    title: "婚姻、疾病與財帛",
    author: "周清河",
    school: "其他名家",
    era: "當代",
    chunks: 152,
    tags: ["其他名家", "婚姻", "疾病", "財帛", "應用"],
    intro: "周清河專論三大人生議題——婚姻、疾病與財帛——的推斷技法，應用性極強。",
  },
  {
    slug: "許銓仁-紫微斗數第一本書(整理版)",
    urlSlug: "xuquanren-diyiben-ziwei",
    title: "紫微斗數第一本書",
    author: "許銓仁",
    school: "其他名家",
    era: "當代",
    chunks: 102,
    tags: ["其他名家", "四化派", "入門", "第一本書"],
    intro: "許銓仁為初學者編寫的四化派入門書，以思想體系為先導，是接觸四化派最友好的起點。",
  },
  {
    slug: "許銓仁-紫微斗數命理學手冊",
    urlSlug: "xuquanren-minglixue-shouce",
    title: "紫微斗數命理學手冊",
    author: "許銓仁",
    school: "其他名家",
    era: "當代",
    chunks: 61,
    tags: ["其他名家", "四化派", "手冊", "工具書"],
    intro: "許銓仁編寫的四化派命理學工具手冊，是研習欽天四化的重要參考索引。",
  },
  {
    slug: "紫微斗數講義(繁體)",
    urlSlug: "ziwei-jiangyi-fanti",
    title: "紫微斗數講義",
    author: "佚名（臺灣版）",
    school: "其他名家",
    era: "當代",
    chunks: 191,
    tags: ["其他名家", "講義", "繁體", "臺灣"],
    intro: "臺灣版綜合講義，系統介紹紫微斗數基礎知識與宮位星曜斷命方法，是通識參考讀本。",
  },
  {
    slug: "紫微斗數星性母本",
    urlSlug: "ziwei-xingxing-muben",
    title: "紫微斗數星性母本",
    author: "佚名",
    school: "其他名家",
    era: "當代",
    chunks: 116,
    tags: ["其他名家", "星性", "母本", "星曜參考"],
    intro: "系統整理各星星性的綜合性參考底本，覆蓋主星輔星的基本象意，是星曜研究的基礎資料。",
  },
  {
    slug: "紫微斗數分析婚姻大全",
    urlSlug: "ziwei-hunyin-daquan",
    title: "紫微斗數分析婚姻大全",
    author: "佚名",
    school: "其他名家",
    era: "當代",
    chunks: 95,
    tags: ["其他名家", "婚姻", "大全", "專題"],
    intro: "專論紫微斗數婚姻分析的綜合資料，彙集各流派對夫妻宮、桃花星的分析要點。",
  },
  {
    slug: "紫佔經典教程-速斷",
    urlSlug: "zizhan-jingdian-suduan",
    title: "紫微斗數速斷經典教程",
    author: "大有命理",
    school: "其他名家",
    era: "當代",
    chunks: 78,
    tags: ["其他名家", "速斷", "紫微資訊學", "全息"],
    intro: "大有命理以紫微資訊學體系講授速斷技法，結合宇宙全息理論，風格獨特，適合進階參考。",
  },
  {
    slug: "紫微斗數光明",
    urlSlug: "ziwei-guangming",
    title: "紫微斗數光明",
    author: "佚名",
    school: "其他名家",
    era: "當代",
    chunks: 74,
    tags: ["其他名家", "易學", "宮位", "星曜"],
    intro: "以易學五術為框架介紹紫微斗數的綜合性講義，涵蓋宮位含義與星曜基礎性質。",
  },
  {
    slug: "瞭然山人-論命技巧及例項解析(下冊)",
    urlSlug: "liaoran-shanren-lunming-xia",
    title: "論命技巧及例項解析（下冊）",
    author: "瞭然山人",
    school: "其他名家",
    era: "當代",
    chunks: 34,
    tags: ["其他名家", "論命技巧", "例項", "下冊"],
    intro: "瞭然山人論命技巧下冊，以大量實際命例深入演示紫微斗數的論命技法與斷命細節。",
  },
  {
    slug: "令東來-斗數星性",
    urlSlug: "lingdonglai-doushu-xingxing",
    title: "斗數星性",
    author: "令東來",
    school: "其他名家",
    era: "當代",
    chunks: 148,
    tags: ["其他名家", "令東來", "星性", "星曜"],
    intro: "令東來詳述紫微斗數各星的星性與象意，先從祿存講起，體系清晰，是星性學習的重要參考。",
  },
  {
    slug: "盲鬥推流年秘法-速斷流年",
    urlSlug: "mangdou-liunian-mifa",
    title: "盲鬥推流年秘法·速斷流年",
    author: "正吉居士",
    school: "其他名家",
    era: "當代",
    chunks: 28,
    tags: ["其他名家", "盲鬥", "流年", "速斷"],
    intro: "以盲鬥法（超越八字）速斷流年的技法秘錄，通過命例演示直斷流年運勢的實戰思路。",
  },
  {
    slug: "未知-命理講義絕密面授手稿2",
    urlSlug: "mianshoushou-gao-2",
    title: "命理講義絕密面授手稿（第二冊）",
    author: "佚名",
    school: "其他名家",
    era: "當代",
    chunks: 88,
    tags: ["其他名家", "面授", "手稿", "內部資料"],
    intro: "內部面授講義手稿，包含不公開的高階斷命技法，是民間命理師實戰心得的珍貴記錄。",
  },

  // ── 北派河洛 ───────────────────────────────────────────────────────────────
  {
    slug: "方外人-河洛紫微斗數",
    urlSlug: "fangwairen-heluo-ziwei",
    title: "河洛紫微斗數",
    author: "方外人",
    school: "其他名家",
    era: "當代",
    chunks: 62,
    tags: ["北派", "河洛", "紫微斗數", "方外人"],
    intro: "方外人以河洛理數為基礎發展出北派紫微斗數體系，與南方各派思路迥異，是獨特的地方流派。",
  },
];

// ─── Helpers ───────────────────────────────────────────────────────────────

export const SCHOOL_LABELS: Record<SourceSchool, string> = {
  "三合派":   "三合派",
  "四化派":   "四化派",
  "飛星派":   "飛星派",
  "倪師學派": "倪師學派",
  "八字命理": "八字命理（子平）",
  "八字祿命": "八字祿命法",
  "八字盲派": "八字盲派",
  "古籍經典": "古籍經典",
  "其他名家": "其他名家",
};

export const SCHOOL_DESC: Record<SourceSchool, string> = {
  "三合派":   "以宮氣論命，重三方會合，香港中州派代表",
  "四化派":   "以飛化體系論命，重化忌飛化與宮位互動",
  "飛星派":   "以四化飛星為核心，重視動態飛化推演",
  "倪師學派": "倪海廈天紀系列，貫通天地人三才",
  "八字命理": "子平法為主軸，格局取用與調候並重",
  "八字祿命": "以納音五行與神煞為核心，歷史最悠久",
  "八字盲派": "意象直斷，不依賴固定框架，以象取象",
  "古籍經典": "傳世古籍與經典原典",
  "其他名家": "跨派系名家著作與綜合命理資料",
};

export function getSourceBook(urlSlug: string): SourceBook | undefined {
  return SOURCE_BOOKS.find(b => b.urlSlug === urlSlug || b.slug === urlSlug);
}

export function getSourcesBySchool(): Map<SourceSchool, SourceBook[]> {
  const map = new Map<SourceSchool, SourceBook[]>();
  const order: SourceSchool[] = [
    "三合派", "四化派", "飛星派", "倪師學派",
    "八字命理", "八字祿命", "八字盲派", "古籍經典", "其他名家"
  ];
  for (const school of order) {
    map.set(school, []);
  }
  for (const book of SOURCE_BOOKS) {
    map.get(book.school)!.push(book);
  }
  return map;
}
